#
# Code generated by restrun "0.1.0".
#
# Removing this comment from this file will exclude it from automatic generation target
# and it will not be updated, unless the file contents are empty.
# If you wish to make special modifications to the auto-generated code,
# please remove this comment.
#
# For more information about restrun,
# please refer to https://github.com/yassun7010/restrun .
#

import typing_extensions

from restrun.core import http
from restrun.core.operation import PostOperation

from ...schemas import order


class StoreOrderJsonResponse(typing_extensions.TypedDict):
    pass


class PostStoreOrderResponseBody(order.Order):
    pass


class PostStoreOrder(PostOperation):
    @classmethod
    @property
    def path(cls) -> "http.URL":
        return "/store/order"

    def post(
        self,
    ) -> "PostStoreOrderResponseBody":
        """
        Place an order for a pet

        Place a new order in the store
        """

        return self._client.post(
            self.path,
            response_type=PostStoreOrderResponseBody,
        )
