#
# Code generated by restrun "0.1.0".
#
# Removing this comment from this file will exclude it from automatic generation target
# and it will not be updated, unless the file contents are empty.
# If you wish to make special modifications to the auto-generated code,
# please remove this comment.
#
# For more information about restrun,
# please refer to https://github.com/yassun7010/restrun .
#
import typing


from restrun.core import http
from restrun.core.operation import (
    GetOperation,
)


class PetFindByStatusQueryParameters(typing.TypedDict):
    status: "typing.Literal['available','pending','sold']"


GetPetFindByStatusResponseBody = typing.Literal[None]


class GetPetFindByStatus(GetOperation):
    @classmethod
    @property
    def path(cls) -> "http.URL":
        return "/pet/findByStatus"

    def get(
        self,
    ) -> "GetPetFindByStatusResponseBody":
        """
        Finds Pets by status

        Multiple status values can be provided with comma separated strings
        """

        return self._client.get(
            self.path,
            response_body_type=GetPetFindByStatusResponseBody,
        )
