#
# Code generated by restrun "0.1.0".
#
# Removing this comment from this file will exclude it from automatic generation target
# and it will not be updated, unless the file contents are empty.
# If you wish to make special modifications to the auto-generated code,
# please remove this comment.
#
# For more information about restrun,
# please refer to https://github.com/yassun7010/restrun .
#

import typing_extensions
from restrun.core import http
from restrun.core.operation import (
    PutOperation,
)

from ...schemas import pet


class PetJsonResponse(typing_extensions.TypedDict):
    pass


class PutPetResponseBody(pet.Pet):
    pass


class PutPet(PutOperation):
    @classmethod
    @property
    def path(cls) -> "http.URL":
        return "/pet"

    def put(
        self,
    ) -> "PutPetResponseBody":
        """
        Update an existing pet

        Update an existing pet by Id
        """

        return self._client.put(
            self.path,
            response_type=PutPetResponseBody,
        )
