#
# Code generated by restrun "0.1.0".
#
# Removing this comment from this file will exclude it from automatic generation target
# and it will not be updated, unless the file contents are empty.
# If you wish to make special modifications to the auto-generated code,
# please remove this comment.
#
# For more information about restrun,
# please refer to https://github.com/yassun7010/restrun .
#
import datetime
import typing

import pydantic

from restrun.core.model import Model


class Order(Model):
    id: typing.Annotated[int, pydantic.Field()]

    petId: typing.Annotated[int, pydantic.Field()]

    quantity: typing.Annotated[int, pydantic.Field()]

    shipDate: typing.Annotated[datetime.datetime, pydantic.Field()]

    status: typing.Annotated[
        typing.Literal["placed", "approved", "delivered"],
        pydantic.Field(
            description="""
                Order Status
                """,
        ),
    ]

    complete: typing.Annotated[bool, pydantic.Field()]
