#
# Code generated by restrun "0.1.0".
#
# Removing this comment from this file will exclude it from automatic generation target
# and it will not be updated, unless the file contents are empty.
# If you wish to make special modifications to the auto-generated code,
# please remove this comment.
#
# For more information about restrun,
# please refer to https://github.com/yassun7010/restrun .
#
import textwrap
import typing

import pydantic

from restrun.core.model import Model

from . import category, tag


class Pet(Model):
    id: typing.Annotated[int, pydantic.Field()]

    name: typing.Annotated[str, pydantic.Field()]

    category: typing.Annotated[category.Category, pydantic.Field()]

    photoUrls: typing.Annotated[list[str], pydantic.Field()]

    tags: typing.Annotated[list[tag.Tag], pydantic.Field()]

    status: typing.Annotated[
        typing.Literal["available", "pending", "sold"],
        pydantic.Field(
            description=textwrap.dedent(
                """
                pet status in the store
                """
            ).strip(),
        ),
    ]
    """
    pet status in the store
    """
