#
# Code generated by restrun "0.1.0".
#
# Removing this comment from this file will exclude it from automatic generation target
# and it will not be updated, unless the file contents are empty.
# If you wish to make special modifications to the auto-generated code,
# please remove this comment.
#
# For more information about restrun,
# please refer to https://github.com/yassun7010/restrun .
#

import typing_extensions
from restrun.core import http
from restrun.core.operation import (
    PostOperation,
)

from ...schemas import user


class UserCreateWithListJsonResponse(typing_extensions.TypedDict):
    pass


class PostUserCreateWithListResponseBody(user.User):
    pass


class PostUserCreateWithList(PostOperation):
    @classmethod
    @property
    def path(cls) -> "http.URL":
        return "/user/createWithList"

    def post(
        self,
    ) -> "PostUserCreateWithListResponseBody":
        """
        Creates list of users with given input array
        """

        return self._client.post(
            self.path,
            response_type=PostUserCreateWithListResponseBody,
        )
