#
# Code generated by restrun "0.1.0".
#
# Removing this comment from this file will exclude it from automatic generation target
# and it will not be updated, unless the file contents are empty.
# If you wish to make special modifications to the auto-generated code,
# please remove this comment.
#
# For more information about restrun,
# please refer to https://github.com/yassun7010/restrun .
#
from typing import Literal, Self

from typing_extensions import override

from restrun.core.client import RestrunMockClient
from restrun.exception import RestrunError

from ..resources.v1_pets import get_v1_pets
from .client import PetstoreClient
from .mixins import bearer_token_login_mixin


class PetstoreMockClient(
    bearer_token_login_mixin.MockBearTokenLoginMixin, RestrunMockClient, PetstoreClient
):
    @override
    def inject_get_response_body(
        self,
        url: Literal["https://petstore3.swagger.io/api/v1/pets"],
        response_body: get_v1_pets.GetV1PetsRequestResponseBody | RestrunError,
    ) -> "Self":
        self._client.inject_get_response_body(url, response_body)

        return self
