#
# Code generated by restrun "0.1.0".
#
# Removing this comment from this file will exclude it from automatic generation target
# and it will not be updated, unless the file contents are empty.
# If you wish to make special modifications to the auto-generated code,
# please remove this comment.
#
# For more information about restrun,
# please refer to https://github.com/yassun7010/restrun .
#
import typing

import pydantic

from restrun.core.model import Model


class Category(Model):
    id: typing.Annotated[int, pydantic.Field()]

    name: typing.Annotated[str, pydantic.Field()]
