#
# Code generated by restrun "$RESTRUN_VERSION". DO NOT EDIT.
# For more information about restrun, please refer to https://github.com/yassun7010/restrun .
#
from typing import Self

from restrun.core.client import RestrunClient
from restrun.core.endpoint import Endpoint

class PetstoreClient(RestrunClient):
    """
    Code generated by restrun "$RESTRUN_VERSION".
    """
