#
# Code generated by restrun "0.1.0".
#
# Removing this comment from this file will exclude it from automatic generation target
# and it will not be updated.
# If you wish to make special modifications to the auto-generated code,
# please remove this comment.
#
# For more information about restrun,
# please refer to https://github.com/yassun7010/restrun .
#
from typing import Literal

from typing_extensions import override

from restrun.core.client import RestrunClient
from restrun.exception import URLNotSupportedError


from ..resources import v1_pets


from .mixins import (
    bearer_token_login_mixin,
)


class PetstoreClient(bearer_token_login_mixin.BearerTokenLoginMixin, RestrunClient):
    @override
    def request(
        self, url: Literal["https://petstore3.swagger.io/api/v1/pets"]
    ) -> "v1_pets.V1PetsResource":
        if url == "https://petstore3.swagger.io/api/v1/pets":
            return v1_pets.V1PetsResource(self._client)

        else:
            raise URLNotSupportedError(url)
