#
# Code generated by restrun "$RESTRUN_VERSION". DO NOT EDIT.
# For more information about restrun,
# please refer to https://github.com/yassun7010/restrun .
#

from restrun.core.client import RestrunMockClient

from .client import PetstoreClient


class PetstoreMockClient(RestrunMockClient, PetstoreClient):
    """
    Code generated by restrun "$RESTRUN_VERSION".
    """
