#
# Code generated by restrun "0.1.0".
#
# Removing this comment from this file will exclude it from automatic generation target
# and it will not be updated.
# If you wish to make special modifications to the auto-generated code,
# please remove this comment.
#
# For more information about restrun,
# please refer to https://github.com/yassun7010/restrun .
#
from typing import Self, Literal

from restrun.core.client import RestrunMockClient
from restrun.exception import RestrunError

from .client import PetstoreClient
from .mixins import (
    bearer_token_login_mixin,
)


from ..resources.v1_pets.get_v1_pets import GetV1PetsRequestResponseBody


class PetstoreMockClient(
    bearer_token_login_mixin.MockBearTokenLoginMixin, RestrunMockClient, PetstoreClient
):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def request(self, url):
        raise NotImplementedError()

    def inject_get_response_body(
        self,
        url: Literal["https://petstore3.swagger.io/api/v1/pets"],
        response_body: GetV1PetsRequestResponseBody | RestrunError,
    ) -> "Self":
        self._client.inject_get_response_body(url, response_body)

        return self
