#
# Code generated by restrun "0.1.0".
#
# Removing this comment will exclude this file from automatic generation target
# and it will not be updated.
# If you wish to make special modifications to the auto-generated code,
# please remove this comment.
#
# For more information about restrun,
# please refer to https://github.com/yassun7010/restrun .
#

from restrun.core.client import RestrunRealClient

from .client import PetstoreClient


class PetstoreRealClient(RestrunRealClient, PetstoreClient):
    """
    Code generated by restrun "0.1.0".
    """
