#
# Code generated by restrun "0.1.0".
#
# Removing this comment from this file will exclude it from automatic generation target
# and it will not be updated, unless the file contents are empty.
# If you wish to make special modifications to the auto-generated code,
# please remove this comment.
#
# For more information about restrun,
# please refer to https://github.com/yassun7010/restrun .
#

from restrun.core.client import RestrunRealClient
from restrun.core.request import RequestRealClient

from .client import PetstoreClient
from .mixins import (
    bearer_token_login_mixin,
)


class PetstoreRealClient(
    bearer_token_login_mixin.RealBearTokenLoginMixin, RestrunRealClient, PetstoreClient
):
    def __init__(self, client: RequestRealClient) -> None:
        self._real_client = client

    @property
    def _client(self) -> RequestRealClient:
        return self._real_client
