#
# Code generated by restrun "0.1.0".
#
# Removing this comment from this file will exclude it from automatic generation target
# and it will not be updated, unless the file contents are empty.
# If you wish to make special modifications to the auto-generated code,
# please remove this comment.
#
# For more information about restrun,
# please refer to https://github.com/yassun7010/restrun .
#
from typing import Literal, Self, overload

from restrun.core.client import RestrunMockClient
from restrun.exceptions import RestrunError
from typing_extensions import override

from ..resources.pet_pet_id import post_pet_pet_id
from ..resources.store_inventory import get_store_inventory
from ..resources.user import post_user
from ..resources.user_login import get_user_login
from ..resources.user_logout import get_user_logout
from ..resources.user_username import put_user_username
from .client import NewCommandSampleClient


class NewCommandSampleMockClient(RestrunMockClient, NewCommandSampleClient):
    @overload
    def inject_get_response(
        self,
        url: Literal["https://example.com/store/inventory"],
        *,
        response: get_store_inventory.GetStoreInventoryResponseBody | RestrunError,
    ) -> "Self":
        ...

    @overload
    def inject_get_response(
        self,
        url: Literal["https://example.com/user/login"],
        *,
        response: get_user_login.GetUserLoginResponseBody | RestrunError,
    ) -> "Self":
        ...

    @overload
    def inject_get_response(
        self,
        url: Literal["https://example.com/user/logout"],
        *,
        response: get_user_logout.GetUserLogoutResponseBody | RestrunError,
    ) -> "Self":
        ...

    @override
    def inject_get_response(self, url, *, response) -> "Self":
        self._client.inject_get_response(url, response)

        return self

    @overload
    def inject_post_response(
        self,
        url: Literal["https://example.com/user"],
        *,
        response: post_user.PostUserResponseBody | RestrunError,
    ) -> "Self":
        ...

    @overload
    def inject_post_response(
        self,
        url: Literal["https://example.com/pet/{petId}"],
        *,
        response: post_pet_pet_id.PostPetPetIdResponseBody | RestrunError,
    ) -> "Self":
        ...

    @override
    def inject_post_response(self, url, *, response) -> "Self":
        self._client.inject_post_response(url, response)

        return self

    @override
    def inject_put_response(
        self,
        url: Literal["https://example.com/user/{username}"],
        *,
        response: put_user_username.PutUserUsernameResponseBody | RestrunError,
    ) -> "Self":
        self._client.inject_put_response(url, response)

        return self
